### ISSUE TITLE
Dataset availability 

### ISSUE THREAD

**Issue by yoheimatt** [Murtadha44/-Intracranial-Hemorrhage-Segmentation-Using-Deep-Convolutional-Model-U-Net-#1]
It seems the dataset is no longer available for download from physionet.org. 
Do you know if it is just temporary, or there will be another site to download?
Thanks, 
Matt

**Comment by Murtadha44** [comment]
Hi Matt,
Thanks for your interest. The data is unavailable temporarily. We encourage you to check Physionet website in a couple of weeks.

Sincerely,
Murtadha D. Hssayeni, M.Sc.
Florida Atlantic University

**Comment by Murtadha44** [comment]
Hi Matt,
The dataset was updated (You can find it at https://physionet.org/content/ct-ich/1.3.1/)), also I updated the code to use the latest version of the dataset.
